### ISSUE TITLE
esginitialize with NoSectionError for project:cmip6

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-installer#209]
When initializing projects, models, and experiments, esgcet fails with the following error:
Traceback (most recent call last):
  File "/usr/local/conda/envs/esgf-pub/bin/esginitialize", line 4, in <module>
    __import__('pkg_resources').run_script('esgcet==3.2.6', 'esginitialize')
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/pkg_resources/__init__.py", line 741, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1502, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgcet-3.2.6-py2.7.egg/EGG-INFO/scripts/esginitialize", line 195, in <module>
    main(sys.argv[1:])
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgcet-3.2.6-py2.7.egg/EGG-INFO/scripts/esginitialize", line 167, in main
    projectConfigOptions = config.options(projectSection)
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/ConfigParser.py", line 279, in options
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'project:cmip6'
/usr/local/bin

Sorry...
This action did not complete successfully
Please re-run this task until successful before continuing further

Also please review the installation FAQ it may assist you
https://github.com/ESGF/esgf.github.io/wiki/ESGFNode%7CFAQ

There error occurs using the autoinstaller and during manual installation.

**Comment by sashakames** [comment]
Appears that esgprep fetch-ini failed to fetch esg.cmip6.ini (we can take a closer look at the logs)  Perhaps just an intermittent connectivity failure.

**Comment by William-Hill** [comment]
The esg.cmip6.ini file appears to be getting downloaded, but it's empty.
