### ISSUE TITLE
TDS installation fails for 2.5.13 @ NOAA

### ISSUE THREAD

**Issue by LucaCinquini** [ESGF/esgf-installer#264]
When trying to install the latest 2.5.13 release, the script encounters this error (and keeps going). As a consequence, the TDS does not start when the script completes.

========================================

   - A file not contained in any dataset root or subdirectory is not accessible (cannot be downloaded).
   - All published files under a dataset root or subdirectory are accessible and visible
   through THREDDS and the web portal.
   - All unpublished files contained in a dataset root or its subdirectories are potentially accessible,
   but not visible in THREDDS or the web portal.
   - The dataset root should not have any symbolic links to directories outside the dataset root.

   Before proceeding, ensure that:

   - Tomcat and TDS are installed and running

   - You have read/write access to the Tomcat content directory.

   - Tomcat and TDS are configured for https and digest
   authentication. For Tomcat V6, the file
   conf/Catalina/localhost/thredds.xml should exist.

   - You have a TDS username/password in tomcat-users.xml.  
   
Directory /esg/content/thredds/esgcet already exists
Traceback (most recent call last):
  File "/usr/local/conda/envs/esgf-pub/bin/esgsetup", line 4, in <module>
    __import__('pkg_resources').run_script('esgcet==3.2.6', 'esgsetup')
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1503, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgcet-3.2.6-py2.7.egg/EGG-INFO/scripts/esgsetup", line 1132, in <module>
    main(sys.argv[1:])
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgcet-3.2.6-py2.7.egg/EGG-INFO/scripts/esgsetup", line 873, in main
    from esgcet.config import loadConfig, initLogging, getThreddsServiceSpecs
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgcet-3.2.6-py2.7.egg/esgcet/config/__init__.py", line 9, in <module>
    from cf_handler import CFHandler
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgcet-3.2.6-py2.7.egg/esgcet/config/cf_handler.py", line 8, in <module>
    import cdtime
ImportError: /usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/../.././libcurl.so.4: undefined symbol: libssh2_scp_recv2

curl http://localhost/thredds

**Comment by thiasB** [comment]
seeing this error on a 2.5.17 installation/upgrade. TDS doesn't start

**Comment by pchengi** [comment]
Not encountered in the 2.6 series.
