### ISSUE TITLE
ESGF3.0 installer - failed in initializing esg_config.yaml file

### ISSUE THREAD

**Issue by muryanto1** [ESGF/esgf-installer#359]
-----------------------------------
Initializing esg_config.yaml file
-----------------------------------

Traceback (most recent call last):
  File "esg_init.py", line 262, in <module>
    init()
  File "esg_init.py", line 256, in init
    yaml.dump(locals(), esg_config)
  File "/usr/local/conda/envs/esgf-pub/lib/python3.6/site-packages/yaml/__init__.py", line 200, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/usr/local/conda/envs/esgf-pub/lib/python3.6/site-packages/yaml/__init__.py", line 188, in dump_all
    dumper.represent(data)
  File "/usr/local/conda/envs/esgf-pub/lib/python3.6/site-packages/yaml/representer.py", line 26, in represent
    node = self.represent_data(data)
  File "/usr/local/conda/envs/esgf-pub/lib/python3.6/site-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/local/conda/envs/esgf-pub/lib/python3.6/site-packages/yaml/representer.py", line 205, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/usr/local/conda/envs/esgf-pub/lib/python3.6/site-packages/yaml/representer.py", line 116, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/local/conda/envs/esgf-pub/lib/python3.6/site-packages/yaml/representer.py", line 51, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/usr/local/conda/envs/esgf-pub/lib/python3.6/site-packages/yaml/representer.py", line 315, in represent_object
    reduce = data.__reduce_ex__(2)
TypeError: cannot serialize '_io.TextIOWrapper' object
Failed at 109: python esg_init.py
Trace:  109 115 0
return code:  0

**Comment by muryanto1** [comment]
"conda create -y -n esgf-pub -c conda-forge -c uvcdat cdutil"  in esg_bootstrap.sh brought in py3.
since we now have py2 cdutil and py3 cdutil in conda-forge. 
By default it seems to bring in py3 cdutil.
To keep python as python2, we can replace the above line with:
"conda create -y -n esgf-pub "python<3" cdutil -c conda-forge -c cdat "

**Comment by William-Hill** [comment]
Resolved by 19ed1b9db97747f69faf0ab73208343c17f432f0
