### ISSUE TITLE
ESGF 3.0 - installing idp node component failed

### ISSUE THREAD

**Issue by muryanto1** [ESGF/esgf-installer#363]
*******************************
Installing IDP Node Components
******************************* 

Traceback (most recent call last):
  File "esg_node.py", line 504, in <module>
    main(node_type_list)
  File "esg_node.py", line 448, in main
    system_component_installation(esg_dist_url, node_type_list)
  File "esg_node.py", line 332, in system_component_installation
    idp.main()
TypeError: main() takes exactly 1 argument (0 given)

**Comment by William-Hill** [comment]
The latest idp node code has been merged into python_devel so this issue should be resolved.
