### ISSUE TITLE
ESGF 3.x installer failed in esg_questionnaire.py

### ISSUE THREAD

**Issue by muryanto1** [ESGF/esgf-installer#463]
`-------------------------------------------------------
Welcome to the ESGF Node installation program! :-)
-------------------------------------------------------
Found existing value for property publisher_db_user: esgcet
Using previously configured publisher DB password
Traceback (most recent call last):
  File "esg_node.py", line 491, in <module>
    main()
  File "esg_node.py", line 368, in main
    esg_questionnaire.initial_setup_questionnaire()
  File "/home/jenkins/repos/esgf-installer/esgf_utilities/esg_questionnaire.py", line 236, in initial_setup_questionnaire
    "installer_uid"], esg_functions.get_tomcat_group_id())
TypeError: an integer is required`

**Comment by muryanto1** [comment]
Not hitting this anymore, not sure if William pushed any changes that fixed this issue.
