### ISSUE TITLE
esgf 3.x installer failed in setup_security configure_postgress

### ISSUE THREAD

**Issue by muryanto1** [ESGF/esgf-installer#494]
```
Installed /usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgf_security-0.1.5-py2.7.egg
Processing dependencies for esgf-security==0.1.5
Searching for SQLAlchemy<=0.7.10,>=0.5.3
Reading http://rainbow.llnl.gov/dist/externals
Reading https://pypi.python.org/simple/SQLAlchemy/
Downloading https://files.pythonhosted.org/packages/a1/12/550cd1743c57be079694a378d4c344605b94313f141b4018c140a94914a9/SQLAlchemy-0.7.10.tar.gz#sha256=77aa39d65c9d043eba6ba329b359ff867424fd6c403b7c0cb112b65e507e1d66
Best match: SQLAlchemy 0.7.10
Processing SQLAlchemy-0.7.10.tar.gz
Writing /tmp/easy_install-hVI3Ch/SQLAlchemy-0.7.10/setup.cfg
Running SQLAlchemy-0.7.10/setup.py -q bdist_egg --dist-dir /tmp/easy_install-hVI3Ch/SQLAlchemy-0.7.10/egg-dist-tmp-kdkzT8
Moving SQLAlchemy-0.7.10-py2.7-linux-x86_64.egg to /usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages
Adding SQLAlchemy 0.7.10 to easy-install.pth file

Installed /usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/SQLAlchemy-0.7.10-py2.7-linux-x86_64.egg
Finished processing dependencies for esgf-security==0.1.5
Traceback (most recent call last):
  File "esg_node.py", line 441, in <module>
    main()
  File "esg_node.py", line 323, in main
    system_component_installation(esg_dist_url, node_type_list)
  File "esg_node.py", line 198, in system_component_installation
    esg_security.setup_security(node_type_list, esg_dist_url)
  File "/home/jenkins/repos/esgf-installer/idp_node/esg_security.py", line 39, in setup_security
    configure_postgress(node_type_list, esg_dist_url, config["esgf_security_version"])
  File "/home/jenkins/repos/esgf-installer/idp_node/esg_security.py", line 101, in configure_postgress
    esg_functions.stream_subprocess_output(esgf_security_initialize_command)
  File "/home/jenkins/repos/esgf-installer/esgf_utilities/esg_functions.py", line 392, in stream_subprocess_output
    raise SubprocessError({"stdout": process.stdout, "stderr": process.stderr, "returncode": process.returncode})
esgf_utilities.esg_exceptions.SubprocessError: {'returncode': 1, 'stderr': None, 'stdout': <closed file '<fdopen>', mode 'rb' at 0x7fc5e9eab4b0>}
```

**Comment by nathanlcarlson** [comment]
@muryanto1 Hello Lina, I've been looking over this, but could not replicate the issue. So it may take a moment to figure out. Thanks for finding it.

**Comment by nathanlcarlson** [comment]
@muryanto1 I found the problem, the db password has a new line character being appended to the end of it.
```
DEBUG - esg_functions.py - 386 - stream_subprocess_output - 08/29/2018 03:18:26 PM - Raw command string: esgf_security_initialize --dburl dbsuper:{thepassword}
@localhost:5432/esgcet -c
DEBUG - esg_functions.py - 388 - stream_subprocess_output - 08/29/2018 03:18:26 PM - shlex.split ['esgf_security_initialize', '--dburl', 'dbsuper:{thepassword}', '@localhost:5432/esgcet', '-c']
```

**Comment by nathanlcarlson** [comment]
Well the newline is being appended, more accurately it has a newline character on it

**Comment by nathanlcarlson** [comment]
@muryanto1 This will be a fix on our end I believe and will get to work on that. As well as fixing the logging.

**Comment by muryanto1** [comment]
Thanks Nathan!
