### ISSUE TITLE
esgf 3.x installer failed in "Running esginitialize" step

### ISSUE THREAD

**Issue by muryanto1** [ESGF/esgf-installer#496]
```
Enabling schema version control ...
Schema version control enabled.

   Checking that database esgcet is up-to-date:
   Running 'esginitialize -c':
   

*******************************
Running esginitialize
******************************* 

Traceback (most recent call last):
  File "esg_node.py", line 441, in <module>
    main()
  File "esg_node.py", line 323, in main
    system_component_installation(esg_dist_url, node_type_list)
  File "esg_node.py", line 184, in system_component_installation
    esg_publisher.main()
  File "/home/jenkins/repos/esgf-installer/data_node/esg_publisher.py", line 268, in main
    run_esginitialize()
  File "/home/jenkins/repos/esgf-installer/data_node/esg_publisher.py", line 159, in run_esginitialize
    esginitialize_process = esg_functions.call_subprocess("esginitialize -c")
  File "/home/jenkins/repos/esgf-installer/esgf_utilities/esg_functions.py", line 420, in call_subprocess
    raise SubprocessError({"stdout": command_process_stdout, "stderr": command_process_stderr, "returncode": command_process.returncode})
esgf_utilities.esg_exceptions.SubprocessError: {'returncode': 1, 'stderr': 'Traceback (most recent call last):\n  File "/usr/local/conda/envs/esgf-pub/bin/esginitialize", line 4, in <module>\n    __import__(\'pkg_resources\').run_script(\'esgcet==3.4.9\', \'esginitialize\')\n  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script\n    self.require(requires)[0].run_script(script_name, ns)\n  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1500, in run_script\n    exec(code, namespace, namespace)\n  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgcet-3.4.9-py2.7.egg/EGG-INFO/scripts/esginitialize", line 195, in <module>\n    main(sys.argv[1:])\n  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgcet-3.4.9-py2.7.egg/EGG-INFO/scripts/esginitialize", line 81, in main\n    config = loadConfig(init_dir)\n  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgcet-3.4.9-py2.7.egg/esgcet/config/config.py", line 284, in loadConfig\n    config = loadConfig1(init_dir, project, load_projects)\n  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgcet-3.4.9-py2.7.egg/esgcet/config/config.py", line 236, in loadConfig1\n    configFile = getConfigFile(init_dir, project)\n  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgcet-3.4.9-py2.7.egg/esgcet/config/config.py", line 259, in getConfigFile\n    raise ESGPublishError("No project configuration file specified, try setting \'%s"%default_envname)\nesgcet.exceptions.ESGPublishError: No project configuration file specified, try setting \'ESGTESTINI\n', 'stdout': ''}

Jenkins build full log can be found at: http://aims1:8080/jenkins/job/esgf_3.x_install/46/console
```

**Comment by nathanlcarlson** [comment]
The problem causing the error is that `/esg/config/esgcet/esg.test.ini` does not exist when it is needed.

The reason it does not exist seems to be here:
```

   Fetching new esg.<project>.ini files from github:
   Running 'esgfetchini' -k:
   

Fetching project(s) config:   0% | 0/20 files
Fetching project(s) config:   5% | 1/20 files
Fetching project(s) config:  10% | 2/20 files
Fetching project(s) config:  15% | 3/20 files
Fetching project(s) config:  20% | 4/20 files
Fetching project(s) config:  25% | 5/20 files
Fetching project(s) config:  30% | 6/20 files
Fetching project(s) config:  35% | 7/20 files
Fetching project(s) config:  40% | 8/20 files
Fetching project(s) config:  45% | 9/20 files
Fetching project(s) config:  50% | 10/20 files
Fetching project(s) config:  55% | 11/20 files
Fetching project(s) config:  60% | 12/20 files
Fetching project(s) config:  65% | 13/20 files
Fetching project(s) config:  70% | 14/20 filesUpdating configuration file /esg/config/esgcet/esg.ini
esg_ini_path: /esg/config/esgcet/esg.ini
```

The 6 of the 20 (appearently) *.ini files are not fetched for whatever reason.
The file the does the fetching is here https://github.com/ESGF/esgf-prepare/blob/master/esgprep/fetchini/main.py

**Comment by nathanlcarlson** [comment]
Here is where the *.ini files live
https://github.com/ESGF/config/tree/master/publisher-configs/ini

**Comment by nathanlcarlson** [comment]
To follow up on this, the installer made it to the end. After a cursory inspection it appears only `thredds` is not functioning properly. Anyway, that is a separate issue. I am going to leave this open as a reminder to properly handle networking errors such as this.
