### ISSUE TITLE
esgf 3.x installer ran to completion (auto installer), but thredds is not up

### ISSUE THREAD

**Issue by muryanto1** [ESGF/esgf-installer#497]
Full log can be found at:
http://aims1:8080/jenkins/job/esgf_3.x_install/47/console

Finished!...
In order to see if this node has been installed properly you may direct your browser to:
http://esgf-dev1.llnl.gov/thredds
http://esgf-dev1.llnl.gov/esg-orp
http://esgf-dev1.llnl.gov/
http://esgf-dev1.llnl.gov/las

thredds and las are not up.

**Comment by nathanlcarlson** [comment]
@muryanto1 There are many useful logs in `/usr/local/tomcat/logs`. This is from `catalina.out` which I think is primary log. (source https://www.unidata.ucar.edu/software/thredds/current/tds/tutorial/TroubleShooting.html )
```
30-Aug-2018 09:57:31.659 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/apache-tomcat-8.5.20/webapps/thredds]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/apache-tomcat-8.5.20/webapps/thredds/WEB-INF/lib/slf4j-log4j12-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/apache-tomcat-8.5.20/webapps/thredds/WEB-INF/lib/log4j-slf4j-impl-2.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
Failed to instantiate SLF4J LoggerFactory
Reported exception:
java.lang.NoClassDefFoundError: org/apache/log4j/Level
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
        at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
        at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:301)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1144)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1878)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Level
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1285)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
        ... 22 more
30-Aug-2018 09:57:46.251 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
30-Aug-2018 09:57:46.254 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [/thredds] startup failed due to previous errors
30-Aug-2018 09:57:46.346 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/apache-tomcat-8.5.20/webapps/thredds] has finished in [14,688] ms
```
This outlines why thredds wasn't started, although it will take some close inspection.

**Comment by nathanlcarlson** [comment]
Since it seems log4j is missing, I went searching for it in the code and found this line commented out.
```
    # # shutil.copyfile("/usr/local/tomcat/webapps/esg-orp/WEB-INF/lib/log4j-1.2.17.jar", "/usr/local/tomcat/webapps/thredds/WEB-INF/lib/log4j-1.2.17.jar")
```
It seems that it is being installed for esg-orp and at one point was being copied over to thredds, but has since been removed.

**Comment by nathanlcarlson** [comment]
Checking the git-blame for that block of code gives this commit https://github.com/ESGF/esgf-installer/commit/31d84c64432c54dca831d9453a4e2da84d92b2b2 .

There is a list of `.jar` files that are being installed in `filters/esg_security_tokenless_filters.py` 
```
return [opensaml_jar, openws_jar, xmltooling_jar, xsgroup_role_jar, commons_collections_jar, serializer_jar, velocity_jar,
                xalan_jar, xercesImpl_jar, xml_apis_jar, xmlsec_jar, joda_time_jar, commons_io_jar, slf4j_api_jar, slf4j_log4j_jar]
```
I believe a `log4j_jar` needs to be added, the `slf4j*` are not sufficient.

**Comment by nathanlcarlson** [comment]
Regarding "las", it appears that the service may be deprecated. I attempted to visit the production node https://esgf-node.llnl.gov/las and it was not found there either.
