### ISSUE TITLE
Installer failing to when running "python setup.py install" in esg-publisher

### ISSUE THREAD

**Issue by nathanlcarlson** [ESGF/esgf-installer#507]
Here is the output from the Jenkins log.
```
Installed /usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/hurry.filesize-0.9-py2.7.egg
Traceback (most recent call last):
  File "esg_node.py", line 441, in <module>
    main()
  File "esg_node.py", line 323, in main
    system_component_installation(esg_dist_url, node_type_list)
  File "esg_node.py", line 184, in system_component_installation
    esg_publisher.main()
  File "/home/jenkins/repos/esgf-installer/data_node/esg_publisher.py", line 266, in main
    setup_publisher()
  File "/home/jenkins/repos/esgf-installer/data_node/esg_publisher.py", line 184, in setup_publisher
    install_publisher()
  File "/home/jenkins/repos/esgf-installer/data_node/esg_publisher.py", line 62, in install_publisher
    esg_functions.stream_subprocess_output("python setup.py install")
  File "/home/jenkins/repos/esgf-installer/esgf_utilities/esg_functions.py", line 396, in stream_subprocess_output
    raise SubprocessError({"stdout": process.stdout, "stderr": process.stderr, "returncode": process.returncode})
esgf_utilities.esg_exceptions.SubprocessError: {'returncode': 1, 'stderr': None, 'stdout': <closed file '<fdopen>', mode 'rb' at 0x7f4a8fde69c0>}
```
I ran the command manually in the environment on the machine.
```
...
Installed /usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgcet-3.4.9-py2.7.egg
Processing dependencies for esgcet==3.4.9
error: netCDF4 1.4.1 is installed but netCDF4==1.4.0 is required by set(['esgprep'])
```
The problem is that `cdf2cim` in the bootstrapper has the following requirement in its `setup.py`
```
'netCDF4>=1.2.1'
```
and `esgprep` has the restrictive requirement in its `setup.py`
```
'netCDF4==1.4.0'
```
So when `pip` gets `netCDF4` for `cdf2cim` it gets the latest version that satisfies the requirement, in this case `1.4.1` which was released August 9, 2018. It must be that `pip` has now added this version to whatever repository is being used.

As a solution, should we simply not install `cdf2cim` during the bootstrap? Or will that cause other problems? @William-Hill What are your thoughts?

**Comment by nathanlcarlson** [comment]
@William-Hill Checkout that issue I reported for more info on the status of this.

**Comment by William-Hill** [comment]
@nathanlcarlson I read your conversation with Guillaume, glad he was able to help.  I was playing around with replacing subprocess calls with Plumbum because Plumbum appears to better at capturing the stdout/stderr vs the stream_subprocess function

**Comment by nathanlcarlson** [comment]
@William-Hill It does look like we can simply not install `cdf2cim` in the bootstraper because it is a requirement in the `esgcet` `setup.py`.
```
install_requires = [
        "psycopg2>=2.0",
        "SQLAlchemy>=0.7.8,!=0.9.5",
        "lxml>=2.0",
        "sqlalchemy_migrate>=0.6",
        "requests>=1.2.0",
        "esgprep>=2.8.1",
        "MyProxyClient>=2.0.1",
        "esgf-pyclient>=0.1.8",
        "esgfpid>=0.7.11",
        "cdf2cim>=0.1.9.0",
    ],
    setup_requires = [
        "psycopg2>=2.0",
        "SQLAlchemy>=0.7.8,!=0.9.5",
        "lxml>=2.0",
        "sqlalchemy_migrate>=0.6",
        "requests>=1.2.0",
]
```

**Comment by nathanlcarlson** [comment]
#510 Explains the solution to this.
