### ISSUE TITLE
Automated publisher test passes publishing and unpublish, but fails run_import_test

### ISSUE THREAD

**Issue by nathanlcarlson** [ESGF/esgf-installer#603]
The `run_import_test` of @muryanto1 's auto publisher test fails with the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgcet/config/cmip6_handler.py", line 5, in <module>
    from cmip6_cv import PrePARE
ImportError: No module named cmip6_cv
```
`cmip6_cv` lives in the `cmor` package in conda. It can be installed with 
```
conda install cmor -c conda-forge
```
or we can add it to the bootstrapper when the conda env is created.

**Comment by William-Hill** [comment]
@nathanlcarlson merged PR to address this
